matrix:
  fast_finish: true
  include:
    - language: python
      python: 2.7
      script:
      - nosetests
      after_success:
      - coveralls
    - language: go
      go: 1.3
      notificaitons:
      email:
        recipients: kuldeepbb.grewal@gmail.com
        on_success: change
        on_failure: always
